services:
  _defaults:
    public: false
    autowire: true

  OxidSupport\Heartbeat\Component\DiagnosticsProvider\Service\DiagnosticsProviderInterface:
    class: OxidSupport\Heartbeat\Component\DiagnosticsProvider\Service\DiagnosticsProvider
    public: true

  OxidSupport\Heartbeat\Component\DiagnosticsProvider\Controller\GraphQL\DiagnosticsController:
    public: true

  OxidSupport\Heartbeat\Component\DiagnosticsProvider\Framework\NamespaceMapper:
    tags: ['graphql_namespace_mapper']
  
  OxidSupport\Heartbeat\Component\DiagnosticsProvider\Framework\PermissionProvider:
    public: true
    tags: ['graphql_permission_provider']