services:

    _defaults:
        autowire: true
        public: false

    OxidSupport\Logger\Logger\ShopRequestLoggerInterface:
        class: OxidSupport\Logger\Logger\ShopRequestLogger

    OxidSupport\Logger\Request\CorrelationIdProviderInterface:
        class: OxidSupport\Logger\Request\CorrelationIdProvider

    OxidSupport\Logger\Logger\ShopRequestLoggerFactory:
        factory: ['OxidSupport\Logger\Logger\ShopRequestLoggerFactory', 'create']
        arguments:
            - '@OxidSupport\Logger\Logger\ShopRequestLoggerInterface'
        public: true

    oxs.logger.channel:
        class: Monolog\Logger
        factory: ['OxidSupport\Logger\Logger\LoggerFactory', 'create']
        arguments:
            - '@OxidSupport\Logger\Request\CorrelationIdProviderInterface'
        public: true
